<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU9fgWRV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU9fgWRV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU9fgWRV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU9fgWRV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU9fgWRV\App_KernelDevDebugContainer([
    'container.build_hash' => 'U9fgWRV',
    'container.build_id' => '638df1fc',
    'container.build_time' => 1731073116,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU9fgWRV');
