<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvIadyc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvIadyc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXvIadyc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXvIadyc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXvIadyc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XvIadyc',
    'container.build_id' => '21066e84',
    'container.build_time' => 1731069591,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvIadyc');
